#+TITLE: Terraform in depth 

* Preface

Terraform is a tool for building, changing, and versioning infrastructure safely and efficiently. 
Terraform can manage existing and popular service providers as well as custom in-house solutions.

We will be using Terraform to provision infrastructure on Azure.
This guide will cover the ins and outs of Terraform and will be a great resource for anyone looking to get started with Terraform.
We will deploy a simple web application as a Docker container on Azure.

* Table of Contents
:CONTENTS:
- [[preface][Preface]]
- [[basic-workflow][Basic Workflow]]
    - [[init][Init]]
    - [[plan][Plan]]
    - [[apply][Apply]]
    - [[destroy][Destroy]]
- [[basic-building-blocks][Basic Building Blocks]]
:END:

* Basic Workflow

The most important commands in Terraform are:
#+BEGIN_SRC
terraform init
terraform plan
terraform apply
terraform destroy
#+END_SRC

** init

The init command is used to initialize a working directory containing Terraform configuration files.
This is the first command that should be run after writing a new Terraform configuration or cloning an existing one from version control.

** plan

The plan command is used to create an execution plan.
Terraform performs a refresh, unless explicitly disabled, and then determines what actions are necessary to achieve the desired state specified in the configuration files.

** apply

The apply command is used to apply the changes required to reach the desired state of the configuration, or the pre-determined set of actions generated by a terraform plan execution plan.

** destroy

The destroy command is used to destroy the Terraform-managed infrastructure.
